config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chapters, except: [:index]
  resources :abouts, only: [:index]
  resources :events, except: [:show]
  resources :contacts, only: [:new, :create]
  root 'about#index'

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message,   :validate => true
    attribute :nickname,  :captcha  => true

    def headers
        {
            :subject => "Contact Form",
            :to => "tonykuoyj@gmail.com",
            :from => %("#{name}" <#{email}>)
        }
    end
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
    before_action :find_chapter, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    def new
        @chapter = Chapter.new
    end

    def create
        @chapter = Chapter.new(chapter_params)

        if @chapter.save
            redirect_to @chapter, notice: "成功儲存！"
        else
            render 'new', notice: "儲存失敗:("
        end
    end

    def show
    end

    def edit
    end

    def update
        if @chapter.update chapter_params
            redirect_to @chapter, notice: "成功儲存！"
        else
            render 'edit', notice: "儲存失敗:("
        end
    end

    def destroy
        @chapter.destroy
        redirect_to chapters_path
    end

    private
    def chapter_params
        params.require(:chapter).permit(:title, :content)
    end

    def find_chapter
        @chapter = Chapter.find(params[:id])
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        if @contact.deliver
            flash.now[:error] = nil
        else
            flash.now[:error] = '訊息傳送失敗'
            render :new
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :find_event, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index]
    
    def index
        @events = Event.all
    end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new event_params

        if @event.save
            redirect_to events_path, notice: "成功儲存！"
        else
            render 'new', notice: "儲存失敗:("
        end
    end

    def edit
    end

    def update
        if @event.update event_params
            redirect_to events_path, notice: "成功儲存！"
        else
            render 'edit', notice: "儲存失敗:("
        end
    end

    def destroy
        @event.destroy
        redirect_to events_path
    end
    
    private
    def event_params
        params.require(:event).permit(:title, :link)
    end

    def find_event
        @event = Event.find(params[:id])
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    class HTMLwithPygments < Redcarpet::Render::HTML
        def block_code(code, language)
            Pygments.highlight(code, lexer: language)
        end
    end
    def to_markdown(content)
        renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true, with_toc_data: true)
        options = {
            autolink:           true,
            fenced_code_blocks: true,
            lax_spacing:        true,
            no_intra_emphasis:  true,
            strikethrough:      true,
            superscript:        true,
            disable_indented_code_blocks: true,
            tables:             true
        }
        Redcarpet::Markdown.new(renderer, options).render(content).html_safe
    end
    
    def to_toc(content)
        renderer = Redcarpet::Render::HTML_TOC.new(nesting_level: 4)
        Redcarpet::Markdown.new(renderer).render(content).html_safe
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/about/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="sticky-top">
                <%= render 'layouts/book' %>
            </div>
        </div>
        <div class="col-md-8">
            <div>
                <br>
                <h3>關於我</h3>
                <br>
                <div class="col align-self-center text-center">
                    <%= image_tag("yaojenkuo.jpg", class: "img-circle") %>
                </div>
                <br>
                <p>郭耀仁畢業於臺灣大學商學研究所，是資料科學與推廣教育的愛好者，目前是新創團隊 Kyosei.ai 的共同創辦人之一，在<a href="http://train.csie.ntu.edu.tw/train/teacher.php?id=103" target="_blank">台灣大學資訊系統訓練班</a>開設多門 R 語言與 Python 的資料科學相關課程，亦與企業合作提供客製化的內訓課程。在 Kyosei.ai 之前任職過上海的新創團隊、台北的軟體公司與銀行，閒暇時喜歡長跑與乒乓球；著有<a href="http://ithelp.ithome.com.tw/users/20103511/ironman/1077" target="_blank"> R 語言使用者的 Python 學習筆記</a>系列文，是 2017 iT 邦幫忙鐵人賽 Big Data 組冠軍。</p>
            </div>
            <br>
            <div class="col align-self-center text-center">
                <a href="https://www.facebook.com/yaojen.kuo.1" target="_blank" class="social_links"><%= fa_stacked_icon "facebook", class: "fa-2x" %></a>
                <a href="https://github.com/yaojenkuo" target="_blank" class="social_links"><%= fa_stacked_icon "github", class: "fa-2x" %></a>
                <a href="https://www.linkedin.com/in/tony-yao-jen-kuo-0412a7b0/" target="_blank" class="social_links"><%= fa_stacked_icon "linkedin", class: "fa-2x" %></a>
            </div>
            <br>
        </div>
    </div>
</div>

app/views/chapters/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
    //this.page.url = '<%= url_for([@chapter, {only_path: false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @chapter.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://rbook-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/chapters/_form.html.erb
<%= simple_form_for @chapter do |f| %>
    <% if @chapter.errors.any? %>
        <h2><%= pluralize(@chapter.errors.count, "error") %> prevented this chapter from saving:</h2>
        <ul>
            <% @chapter.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    <%= f.input :title, label: "標題", required: true %>
    <br>
    <%= f.input :content, label: "內容", as: :text, required: true, :input_html => {:style => 'width: 100%', :rows => 20, class: 'response-project'}%>
    <br>
    <%= f.submit "送出" %>
<% end %>

app/views/chapters/edit.html.erb
<h1>編輯章節</h1>

<%= render "form" %>

app/views/chapters/new.html.erb
<h3>新增章節</h3>

<%= render "form" %>

app/views/chapters/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="sticky-top">
                <%= render 'layouts/book' %>
                <div id="toc">
                    <%= to_toc(@chapter.content) %>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <br>
            <h1><%= @chapter.title %></h1>
            <br>
            <p><%= to_markdown(@chapter.content) %></p>
            <% if user_signed_in? %>
            <div>
                <%= link_to "編輯", edit_chapter_path(@chapter) %>
                <%= link_to "刪除", chapter_path(@chapter), method: :delete, data: {confirm: "確定要刪除這個章節？"} %>
            </div>
            <% end %>
            <%= render 'disqus' %>
        </div>
    </div>
</div>

app/views/contacts/_form.html.erb
<%= simple_form_for @contact do |f| %>
    <% if @contact.errors.any? %>
        <h2><%= pluralize(@contact.errors.count, "error") %> prevented this contact from saving:</h2>
        <ul>
            <% @contact.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    <%= f.input :name, label: "姓名", required: true , placeholder: 'Chandler Bing'%>
    <%= f.input :email, label: "電子郵件", required: true , placeholder: 'chandler@friends.com'%>
    <%= f.input :message, label: "訊息", required: true, as: :text, placeholder: 'Can I interest you in a sarcastic comment?' %>
    <div class="hidden">
        <%= f.input :nickname, hint: 'Leave this field blank' %>
    </div>
    <%= f.submit "送出" %>
<% end %>

app/views/contacts/create.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <%= render 'layouts/book' %>
        </div>
        <div class="col-md-8">
        <br>
            <h3>感謝您的來信</h3>
            <p>我會盡快回覆您！</p>
        </div>
    </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <%= render 'layouts/book' %>
        </div>
        <div class="col-md-8">
        <br>
            <h3>與我聯絡</h3>
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
    <% if @event.errors.any? %>
        <h2><%= pluralize(@event.errors.count, "error") %> prevented this event from saving:</h2>
        <ul>
            <% @event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    <%= f.input :title, label: "標題", required: true %>
    <br>
    <%= f.input :link, label: "連結", required: true %>
    <br>
    <%= f.submit "送出" %>
<% end %>

app/views/events/edit.html.erb
<h1>編輯活動</h1>

<%= render "form" %>

app/views/events/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <%= render 'layouts/book' %>
        </div>
        <div class="col-md-8">
        <br>
            <h3>活動</h3>
            <% if @events.count == 0 %>
                <p>近期沒有活動喔 :)</p>
            <% else %>     
                <% @events.each do |event| %>
                    <h4><%= link_to event.title, event.link, target: "_blank" %></h4>
                    <% if user_signed_in? %>
                        <div>
                            <%= link_to "編輯", edit_event_path(event) %>
                            <%= link_to "刪除", event_path(event), method: :delete, data: {confirm: "確定要刪除這個活動？"} %>
                        </div>
                    <% end %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/events/new.html.erb
<h1>新增活動</h1>

<%= render "form" %>

app/views/layouts/_book.html.erb
<br><br>
<div id="book">
    <div class="col align-self-center">
        <%= image_tag("r_book.jpg", class: "img-fluid rounded mx-auto d-block") %>
    </div>
    <br>
    <div class="col align-self-center">
        <p>實體書由碁峰出版社發行，如果想要購買，可以至<a href="https://www.tenlong.com.tw/products/9789864764822" target="_blank">天瓏網路書店</a>或者<a href="http://www.books.com.tw/products/0010763975" target="_blank">博客來</a>；或者參考我的 Udemy 數位課程<a href="https://www.udemy.com/learn-r-the-easy-way-1/?couponCode=LEARNR" target="_blank">輕鬆學習 R 語言：基礎篇</a>。</p>
    </div>
</div>

app/views/layouts/_chapter_form.html.erb
<%= simple_form_for @chapter do |f| %>
    <% if @chapter.errors.any? %>
        <h2><%= pluralize(@chapter.errors.count, "error") %> prevented this chapter from saving:</h2>
        <ul>
            <% @chapter.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
    <%= f.input :title, label: "標題", required: true %>
    <br>
    <%= f.input :content, label: "內容", required: false %>
    <br>
    <%= f.submit "送出" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <span class="text-muted">&copy; <%= Date.today.year %> 郭耀仁 Yao-Jen Kuo. Powered by Bootstrap 4 and Rails 5.</span>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <div class="container">
    <%= link_to "輕鬆學習 R 語言", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role = "button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          目錄
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <% @chapters = Chapter.all.order('title') %>
          <% @chapters.each do |chapter| %>
                <%= link_to chapter.title, chapter, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <!--
      <li class="nav-item">
        <%= link_to "活動", events_path, class: "nav-link" %>
      </li>
      -->
      <li class="nav-item">
        <%= link_to "與我聯絡", new_contact_path, class: "nav-link" %>
      </li>    
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role = "button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            管理者工具
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "新增章節", new_chapter_path, class: "dropdown-item" %>
            <%= link_to "新增活動", new_event_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "登出", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-107342551-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments)};
      gtag('js', new Date());
      gtag('config', 'UA-107342551-1');
    </script>

    <title>輕鬆學習 R 語言 | Learn R The Easy Way</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- mobile friendly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Facebook sharing -->
    <meta property="og:url"           content="http://www.learn-r-the-easy-way.tw" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="輕鬆學習 R 語言 | Learn R the Easy Way" />
    <meta property="og:description"   content="這是一本閱讀起來不那麼生澀的程式語言書籍，讓原本沒有程式基礎但是工作上有分析需求的使用者，能夠用很輕鬆的方式學會 R 語言，進而應用到工作中，提升工作掌握度。理想的閱讀時間是工作日的午餐時間，我認為最好的學習就是不佔用讀者工作以外的休憩時間。" />
    <meta property="og:image"         content="https://storage.googleapis.com/learn-r-the-easy-way.appspot.com/learn-r-the-easy-way.png" />
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <div class="container">
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% elsif alert %>
          <p class="alert"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
  </body>
</html>